# Bibliotheken importieren

In [1]:
import pandas as pd
import numpy as np

# Datei lesen

In [2]:
df = pd.read_csv('C:\\Users\\Trainee\\Documents\\Portfolioprojekte\\labels_anomalien_f.csv', na_values=['NA', 'NaN', 'None', ''])

# Information der Daten herausnehmen

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10200 entries, 0 to 10199
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   transaktions_id         10200 non-null  str
 1   ist_duplikat_kopie      10200 non-null  int64
 2   ist_iban_abweichung     10200 non-null  int64
 3   ist_betrags_ausreisser  10200 non-null  int64
 4   hat_anomalie            10150 non-null  float64
dtypes: float64(1), int64(3), str(1)
memory usage: 398.6 KB

# Datentyp prüfen

In [4]:
df.dtypes

transaktions_id               str
ist_duplikat_kopie          int64
ist_iban_abweichung         int64
ist_betrags_ausreisser      int64
hat_anomalie              float64
dtype: object

# erste 5 Zeile

In [5]:
df.head()

,transaktions_id,ist_duplikat_kopie,ist_iban_abweichung,ist_betrags_ausreisser,hat_anomalie
0,T000001,0,0,0,0.0
1,T000002,0,0,0,0.0
2,T000003,0,0,0,0.0
3,T000004,0,0,0,0.0
4,T000005,0,0,0,0.0

# Spalte hat_anomalie bereinigen

In [7]:
# prüfung ob es negative Werte gibt
df[df['hat_anomalie'] < 0]

,transaktions_id,ist_duplikat_kopie,ist_iban_abweichung,ist_betrags_ausreisser,hat_anomalie
213,T000214,0,0,0,-1.0
1101,T001102,0,0,0,-1.0
1462,T001463,0,0,0,-1.0
2281,T002282,1,0,0,-1.0
3243,T003244,0,0,0,-1.0
3898,T003899,0,0,0,-1.0
4005,T004006,0,0,0,-1.0
4046,T004047,0,0,0,-1.0
4413,T004414,1,0,0,-1.0
5058,T005059,0,0,0,-1.0
5152,T005153,0,0,0,-1.0
5360,T005361,0,0,0,-1.0
5452,T005453,0,0,0,-1.0
5493,T005494,0,0,0,-1.0
5888,T005889,0,0,0,-1.0
6079,T006080,0,0,0,-1.0
6355,T006356,0,0,0,-1.0
6403,T006404,0,0,0,-1.0
6479,T006480,0,0,0,-1.0
6852,T006853,0,0,0,-1.0
7320,T007321,0,0,0,-1.0
7372,T007373,0,1,0,-1.0
7464,T007465,0,0,0,-1.0
7771,T007772,0,0,0,-1.0
8144,T008145,0,0,0,-1.0
8622,T008623,0,0,0,-1.0
8877,T008878,0,0,0,-1.0
9726,T009727,0,0,0,-1.0
9744,T009745,0,0,0,-1.0
9992,T009993,0,0,0,-1.0

# negative Werte in der Spalte 'hat_anomalie' werden durch nan ersetzt
# und die Spalte als numerisch deklariert

In [ ]:

df.loc[df['hat_anomalie'] < 0, 'hat_anomalie'] = np.nan
df['hat_anomalie'] = pd.to_numeric(df['hat_anomalie'], errors='coerce')

# Spalte hat_annomalie als integer casten

In [11]:
df['hat_anomalie'] = df['hat_anomalie'].astype('Int64')

In [12]:
df.dtypes

transaktions_id             str
ist_duplikat_kopie        int64
ist_iban_abweichung       int64
ist_betrags_ausreisser    int64
hat_anomalie              Int64
dtype: object

In [14]:
print(df.loc[df['hat_anomalie'] < 0, 'hat_anomalie'])

Series([], Name: hat_anomalie, dtype: Int64)

In [17]:
df.head(20)

,transaktions_id,ist_duplikat_kopie,ist_iban_abweichung,ist_betrags_ausreisser,hat_anomalie
0,T000001,0,0,0,0
1,T000002,0,0,0,0
2,T000003,0,0,0,0
3,T000004,0,0,0,0
4,T000005,0,0,0,0
5,T000006,0,0,0,0
6,T000007,0,0,0,0
7,T000008,0,0,0,0
8,T000009,0,0,0,0
9,T000010,0,0,0,0
10,T000011,0,0,0,0
11,T000012,0,0,0,0
12,T000013,0,0,0,0
13,T000014,0,0,0,0
14,T000015,0,0,0,0
15,T000016,0,0,0,0
16,T000017,0,0,0,0
17,T000018,0,0,0,0
18,T000019,0,0,0,0
19,T000020,0,0,0,0

# df als csv speichern

In [ ]:

df.to_csv('labels_anomalien_bereinigt.csv', index=False)