# Biblioteken importieren

In [77]:
import pandas as pd
import numpy as np

# Datei lesen

In [78]:
df = pd.read_csv('C:\\Users\\Trainee\\Documents\\Portfolioprojekte\\rechnungen_f.csv', na_values=['NA', 'NaN', 'None', ''])

# Information der Daten herausnehmen

In [79]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10200 entries, 0 to 10199
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   transaktions_id         10200 non-null  str
 1   rechnungsnummer         10200 non-null  str
 2   lieferanten_id          10200 non-null  str
 3   rechnungsdatum          10080 non-null  str
 4   faelligkeitsdatum       10100 non-null  str
 5   iban                    10200 non-null  str
 6   betrag_eur              10037 non-null  str
 7   waehrung                10200 non-null  str
 8   kostenstelle            10110 non-null  str
 9   buchender_mitarbeiter   10120 non-null  str
 10  ist_duplikat_kopie      10200 non-null  int64
 11  ist_iban_abweichung     10200 non-null  int64
 12  ist_betrags_ausreisser  10200 non-null  int64
dtypes: int64(3), str(10)
memory usage: 1.0 MB

# Datentyp prüfen

In [80]:
df.dtypes

transaktions_id             str
rechnungsnummer             str
lieferanten_id              str
rechnungsdatum              str
faelligkeitsdatum           str
iban                        str
betrag_eur                  str
waehrung                    str
kostenstelle                str
buchender_mitarbeiter       str
ist_duplikat_kopie        int64
ist_iban_abweichung       int64
ist_betrags_ausreisser    int64
dtype: object

# prüft, ob es fehlende Werte gibt und summiere die

In [81]:
df.isna().sum()

transaktions_id             0
rechnungsnummer             0
lieferanten_id              0
rechnungsdatum            120
faelligkeitsdatum         100
iban                        0
betrag_eur                163
waehrung                    0
kostenstelle               90
buchender_mitarbeiter      80
ist_duplikat_kopie          0
ist_iban_abweichung         0
ist_betrags_ausreisser      0
dtype: int64

# Prüfe der ersten 5 Zeile

In [82]:
df.head()

,transaktions_id,rechnungsnummer,lieferanten_id,rechnungsdatum,faelligkeitsdatum,iban,betrag_eur,waehrung,kostenstelle,buchender_mitarbeiter,ist_duplikat_kopie,ist_iban_abweichung,ist_betrags_ausreisser
0,T000001,RE-2026-00052,L003,2026-01-01,2026-01-15,DE34416324838678344342,165.45,EUR,KS-003,Jacob,0,0,0
1,T000002,RE-2026-00084,L009,2026-01-01,2026-01-15,DE27658313688646907154,4241.16,EUR,KS-021,Hermann,0,0,0
2,T000003,RE-2026-00122,L018,2026-01-01,2026-01-22,DE62771578489443956211,1395.5,EUR,KS-011,Holsten,0,0,0
3,T000004,RE-2026-00113,L019,2026-01-01,2026-01-31,DE42624414663978431978,868.05,EUR,KS-022,Kühnert,0,0,0
4,T000005,RE-2026-00104,L020,2026-01-01,2026-01-15,DE38931223102677045064,1768.16,EUR,KS-012,Bärer,0,0,0

# prüfe der letzten 5 Zeile

In [83]:
df.tail()

,transaktions_id,rechnungsnummer,lieferanten_id,rechnungsdatum,faelligkeitsdatum,iban,betrag_eur,waehrung,kostenstelle,buchender_mitarbeiter,ist_duplikat_kopie,ist_iban_abweichung,ist_betrags_ausreisser
10195,T010196,RE-2026-00002,L071,2026-09-29,2026-10-29,DE88948907260834855904,1407.28,EUR,KS-015,Niemeier,0,0,0
10196,T010197,RE-2026-00056,L074,2026-09-29,2026-10-13,DE31889112932957084556,1479.67,EUR,KS-023,Lachmann,0,0,0
10197,T010198,RE-2026-00068,L077,2026-09-29,2026-10-20,DE95136993917430462301,2136.55,EUR,KS-024,Ehlert,0,0,0
10198,T010199,RE-2026-00100,L078,2026-09-29,2026-10-29,DE98624960154356786873,1252.47,EUR,KS-001,Meyer,0,0,0
10199,T010200,RE-2026-00126,L078,2026-09-29,2026-10-13,DE98624960154356786873,1048.64,EUR,KS-020,Misicher,0,0,0

# Datumswerte bereinigen: Wir können die Spalte 'rechnungsdatum' in ein Datumsformat umwandeln, um die Daten für die Analyse der Buchungen nach Datum vorzubereiten.

In [ ]:

df['rechnungsdatum'] = df['rechnungsdatum'].astype(str).str.strip().replace(['', 'nan', 'NaN', 'None'], np.nan).fillna('Unbekannt')

# faelligskeitsdatum bereinigen: Wir können die Spalte 'faelligkeitsdatum' in ein Datumsformat umwandeln, um die Daten für die Analyse der Buchungen nach Fälligkeitsdatum vorzubereiten.

In [ ]:
df['faelligkeitsdatum'] = df['faelligkeitsdatum'].astype(str).str.strip().replace(['', 'nan', 'NaN', 'None'], np.nan).fillna('Unbekannt')
# df['faelligkeitsdatum'] = pd.to_datetime(df['faelligkeitsdatum'],

# prüft, ob es fehlende Werte gibt und summiere die

In [86]:
df.isna().sum()

transaktions_id             0
rechnungsnummer             0
lieferanten_id              0
rechnungsdatum              0
faelligkeitsdatum           0
iban                        0
betrag_eur                163
waehrung                    0
kostenstelle               90
buchender_mitarbeiter      80
ist_duplikat_kopie          0
ist_iban_abweichung         0
ist_betrags_ausreisser      0
dtype: int64

# Beträge saubern und in Zahlen umwandlen

In [ ]:

df['betrag_eur'] = (
    df['betrag_eur']
    .astype(str)
    .str.replace(' €', '', regex=False)
    .str.replace('.', '', regex=False)
    .str.replace(',', '.', regex=False)
)
df['betrag_eur'] = pd.to_numeric(df['betrag_eur'], errors='coerce')

# ungueltige Werte in der spalte 'betrag_eur' behandeln: 
# Wir können die ungueltigen Werte in der Spalte 'betrag_eur' durch den Median der Spalte ersetzen, um die Daten zu bereinigen.

In [ ]:

df['betrag_eur'] = df['betrag_eur'].fillna(df['betrag_eur'].median())

In [89]:
df.isna().sum()

transaktions_id            0
rechnungsnummer            0
lieferanten_id             0
rechnungsdatum             0
faelligkeitsdatum          0
iban                       0
betrag_eur                 0
waehrung                   0
kostenstelle              90
buchender_mitarbeiter     80
ist_duplikat_kopie         0
ist_iban_abweichung        0
ist_betrags_ausreisser     0
dtype: int64

# Daten für die Kostenstellenanalyse vorbereiten: Wir können die Spalte 'kostenstelle' in eine Kategorie umwandeln, 
# um die Daten für die Kostenstellenanalyse vorzubereiten. und leerzeichen entfernen

In [ ]:

df['kostenstelle'] = df['kostenstelle'].astype(str).str.strip().replace(['', 'nan', 'NaN', 'None'], np.nan).fillna('Unbekannt').astype('category')

# Analyse der spalte buchender_mitarbeiter: 
# Wir können die Spalte 'buchender_mitarbeiter' in eine Kategorie umwandeln,
# um die Daten für die Analyse der Buchungen pro Mitarbeiter vorzubereiten. und leerzeichen entfernen

In [ ]:

df['buchender_mitarbeiter'] = df['buchender_mitarbeiter'].astype(str).str.strip().replace(['', 'nan', 'NaN', 'None'], np.nan).fillna('Unbekannt').astype('category')

In [92]:
df.isna().sum()

transaktions_id           0
rechnungsnummer           0
lieferanten_id            0
rechnungsdatum            0
faelligkeitsdatum         0
iban                      0
betrag_eur                0
waehrung                  0
kostenstelle              0
buchender_mitarbeiter     0
ist_duplikat_kopie        0
ist_iban_abweichung       0
ist_betrags_ausreisser    0
dtype: int64

In [93]:
df.dtypes

transaktions_id                str
rechnungsnummer                str
lieferanten_id                 str
rechnungsdatum                 str
faelligkeitsdatum              str
iban                           str
betrag_eur                 float64
waehrung                       str
kostenstelle              category
buchender_mitarbeiter     category
ist_duplikat_kopie           int64
ist_iban_abweichung          int64
ist_betrags_ausreisser       int64
dtype: object

# string Datentyp als Kategorie umwandeln

In [ ]:

for col in df.columns:
    if df[col].dtype == 'str':
        df[col] = df[col].astype('category')

In [95]:
df.dtypes

transaktions_id           category
rechnungsnummer           category
lieferanten_id            category
rechnungsdatum            category
faelligkeitsdatum         category
iban                      category
betrag_eur                 float64
waehrung                  category
kostenstelle              category
buchender_mitarbeiter     category
ist_duplikat_kopie           int64
ist_iban_abweichung          int64
ist_betrags_ausreisser       int64
dtype: object

# df als csv-datei speichern

In [ ]:

df.to_csv('rechnungen_bereinigt.csv', index=False)