# Datenbereinigung der Datei lieferanten_f.csv

# import der Bibliotheken

In [1]:
import pandas as pd
import numpy as np

# Datei lesen

In [2]:
df = pd.read_csv('C:\\Users\\Trainee\\Documents\\Portfolioprojekte\\lieferanten_f.csv', na_values=['NA', 'NaN', 'None', ''])

# prüfe der ersten 5 Zeile

In [3]:
df.head()

,lieferanten_id,lieferanten_name,stadt,plz,offizielle_iban,median_betrag_eur,streuung
0,L001,Dowerg,NaN,33218.0,DE61756828670787846415,2217.42,1.02
1,L002,Schäfer GmbH & Co. KG,Aurich,33890.0,DE82457889219019323607,249.60,1.21
2,L003,Gumprich,Füssen,94026.0,DE34416324838678344342,244.72,1.11
3,L004,Holsten Förster AG & Co. OHG,Burglengenfeld,61559.0,DE82145213734298312066,610.93,0.73
4,L005,Beyer Vollbrecht GmbH & Co. KG,Koblenz,84959.0,DE22868934974325316861,1341.28,0.80

# prüfe der letzten 5 Zeile

In [4]:
df.tail()

,lieferanten_id,lieferanten_name,stadt,plz,offizielle_iban,median_betrag_eur,streuung
75,L076,Aumann KG,München,75204.0,DE92269538311202306933,1943.75,0.96
76,L077,Drewes Bolzmann GmbH,Bersenbrück,22941.0,DE95136993917430462301,1305.23,0.77
77,L078,Drubin KG,Schlüchtern,86774.0,DE98624960154356786873,1078.29,0.66
78,L079,Lorch,Ribnitz-Damgarten,91334.0,DE55117480141337509982,2577.94,1.09
79,L080,Butte,Gerolzhofen,81206.0,DE97332951796406441392,2436.19,0.84

# check der Datentyp

In [5]:
df.dtypes

lieferanten_id           str
lieferanten_name         str
stadt                    str
plz                  float64
offizielle_iban          str
median_betrag_eur    float64
streuung             float64
dtype: object

# prüft, ob es fehlende Werte gibt und summiere die

In [6]:
df.isna().sum()

lieferanten_id       0
lieferanten_name     0
stadt                5
plz                  5
offizielle_iban      4
median_betrag_eur    1
streuung             0
dtype: int64

# prüfung der numerischen spalten

In [7]:
df.describe()

                 plz  median_betrag_eur   streuung
count      75.000000          79.000000  80.000000
mean    64174.853333        1396.229367   0.942375
std    113136.289918         820.225728   0.204192
min       123.000000        -250.000000   0.610000
25%     27473.500000         757.325000   0.765000
50%     52427.000000        1274.140000   0.955000
75%     75238.500000        2137.635000   1.112500
max    999999.000000        2902.630000   1.280000

# numerische spalten berechnen: Wir haben 2 numerische Spalten. 
# Diese sind: 'plz' und 'median_betrab_eur'.
# in Deustchland gibt es 5 Ziffern in der Postleitzahl.
# Zur Berinigung der Daten können wir die Postleitzahlen auf 5 Ziffern überprüfen 
# Dafür wird eine Funktion erstellt, die überprüft, ob die Postleitzahl 5 Ziffern hat.

In [ ]:

def check_plz(plz):
    if pd.isna(plz):
        return np.nan
    # in string umwandeln und eventuell nachkommastellen entfernen
    s = str(plz).strip()
    if '.' in s:
        s = s.split('.')[0]
    # nur Ziffern behalten falls es Buchstaben gibt
    s = ''.join(filter(str.isdigit, s))
    # Auf länge prüfen und korrigieren
    if len(s) == 5:
        return str(s)
    elif len(s) == 4:
        return '0' + str(s)  # führende Nullen hinzufügen
    else:
        return np.nan  # ungültige Postleitzahl

# kontrolliere welche Postleitzahlen ungültig verwofen wurden
Spalte plz als category umwandeln

In [ ]:
df['plz'] = df['plz'].apply(check_plz)

ungueltige_plz = df[df['plz'].isna() & df['plz'].notna()] 

print("Ungueltige Postleitzahlen:" , len(ungueltige_plz))
print(ungueltige_plz[['lieferanten_id', 'lieferanten_name', 'plz']])

Ungueltige Postleitzahlen: 0
Empty DataFrame
Columns: [lieferanten_id, lieferanten_name, plz]
Index: []

# negative Werte in der Spalte 'median_betrag_eur' überprüfen

In [ ]:

spalte  = 'median_betrag_eur'
negative_values = df.loc[:, spalte] < 0
df.loc[negative_values, spalte] = np.nan
df[spalte] = pd.to_numeric(df[spalte], errors='coerce')

# prüft, ob es keine negativen Werte mehr gibt

In [11]:
df.describe()

       median_betrag_eur   streuung
count          78.000000  80.000000
mean         1417.334872   0.942375
std           803.654506   0.204192
min           189.060000   0.610000
25%           771.690000   0.765000
50%          1277.185000   0.955000
75%          2140.827500   1.112500
max          2902.630000   1.280000

In [12]:
df.dtypes

lieferanten_id           str
lieferanten_name         str
stadt                    str
plz                      str
offizielle_iban          str
median_betrag_eur    float64
streuung             float64
dtype: object

In [13]:
# lieferanten_id und lieferanten_name stadt und offizielle_iban als kategorische Spalten umwandlen
#df['lieferanten_id'] = df['lieferanten_id'].astype('category')
#df['lieferanten_name'] = df['lieferanten_name'].astype('category')
#df['stadt'] = df['stadt'].astype('category')
#df['offizielle_iban'] = df['offizielle_iban'].astype('category')

# String spalten analyse: Es gibt 4 Spalten mit String Werten. Diese sind: 'lieferant_id', 'liferenten_name', 'stadt' und 'offizielle_iban'.
# Wir können uns die unique Werte dieser Spalten anschauen, um zu sehen, welche Werte in diesen Spalten vorkommen.

In [ ]:

for i in [0, 1, 2, 4]:
    print(df.iloc[:, i].unique())

<StringArray>
['L001', 'L002', 'L003', 'L004', 'L005', 'L006', 'L007', 'L008', 'L009',
 'L010', 'L011', 'L012', 'L013', 'L014', 'L015', 'L016', 'L017', 'L018',
 'L019', 'L020', 'L021', 'L022', 'L023', 'L024', 'L025', 'L026', 'L027',
 'L028', 'L029', 'L030', 'L031', 'L032', 'L033', 'L034', 'L035', 'L036',
 'L037', 'L038', 'L039', 'L040', 'L041', 'L042', 'L043', 'L044', 'L045',
 'L046', 'L047', 'L048', 'L049', 'L050', 'L051', 'L052', 'L053', 'L054',
 'L055', 'L056', 'L057', 'L058', 'L059', 'L060', 'L061', 'L062', 'L063',
 'L064', 'L065', 'L066', 'L067', 'L068', 'L069', 'L070', 'L071', 'L072',
 'L073', 'L074', 'L075', 'L076', 'L077', 'L078', 'L079', 'L080']
Length: 80, dtype: str
<StringArray>
[                               'Dowerg',
                 'Schäfer GmbH & Co. KG',
                              'Gumprich',
          'Holsten Förster AG & Co. OHG',
        'Beyer Vollbrecht GmbH & Co. KG',
                            'Tlustek AG',
                    'Metz Schuster GmbH',
                            'Vollbrecht',
                               'Hein AG',
                           '  Ortmann  ',
                                 'Hesse',
                              'Wende AG',
                              'Mosemann',
             'Lübs Franke GmbH & Co. KG',
                           '  Patberg  ',
                      'Niemeier Bähr AG',
                            'Neureuther',
                       'auch Schlauchin',
              'Dussen van Hentschel GbR',
            'Boucsein Stiftung & Co. KG',
        'Staude Neureuther AG & Co. OHG',
                 'Sorgatz GmbH & Co. KG',
                                 'Kambs',
                 'Holsten GmbH & Co. KG',
                            'Weller GbR',
                       'Adler Krebs GbR',
                          'Bohlander KG',
                                'Franke',
                'Dussen van Roskoth GbR',
        'Haase Staude Stiftung & Co. KG',
                  'Anders GmbH & Co. KG',
                          'Koch II GmbH',
                                  'Döhn',
                                'Häring',
                                'Löchel',
                                 'Trapp',
       'Säuberlich Rohleder AG & Co. KG',
                                'Hering',
        'Barth Gieß Stiftung & Co. KGaA',
            'Hartung Gute GmbH & Co. KG',
                    'Bohnbach Wirth GbR',
                              'Salz GbR',
                             'Krause KG',
             'Losekann Bohnbach OHG mbH',
                     'Kusch Textor GmbH',
                  'Rogge Ackermann GmbH',
          'Steuer Hamann GmbH & Co. OHG',
                           'Weitzel GbR',
                               'Wilmsen',
                            'Finke KGaA',
                              'Roht GbR',
 'Schmidtke Tschentscher GmbH & Co. OHG',
                           '  Hofmann  ',
                     'Käster Juncken KG',
                       'Ladeck Kabus KG',
                                'Kramer',
                              'Hartmann',
                              'Stiebitz',
                   'Scheel Rose OHG mbH',
             'Junken Hahn GmbH & Co. KG',
                           '  Weiß KG  ',
                   'Scholtz AG & Co. KG',
             'Geisel auch Schlauchin KG',
                              '  Kohl  ',
                               'Schinke',
                               'Seifert',
                              'Fliegner',
                                'Scheel',
                               'Schmidt',
                       'Heser Karge GbR',
                   'Röhricht Werner GbR',
                    'Süßebier Henk GmbH',
                 '  Jäkel Hermann GbR  ',
                'Warmer GmbH & Co. KGaA',
                      'Jacobi Jäckel AG',
                             'Aumann KG',
                  'Drewes Bolzmann GmbH',
                             'Drubin KG',
                                 'Lorch',
                                 'Butte']
Length: 80, dtype: str
<StringArray>
[                     nan,                 'Aurich',                 'Füssen',
         'Burglengenfeld',                'Koblenz',                'Stendal',
                'Kemnath',             'Eberswalde',             'Lobenstein',
              'Sonneberg',                   'Roth',                 'Döbeln',
                'Rastatt',                 'Werdau',              'Hechingen',
             'Zeulenroda',           'Freudenstadt',                'Geldern',
            'Wernigerode',               'Lüneburg',             'Biedenkopf',
            'Ludwigsburg',              'Gütersloh',         'Wolfratshausen',
                   'Olpe',            'Schweinfurt',            'Gerolzhofen',
                'Grimmen',              'Forchheim',        'Bad Liebenwerda',
                  'Regen',                 'Dachau',                 'Jülich',
                'Lörrach',              'Havelberg',          'Sondershausen',
                 'Bützow',                  'Greiz',       'Schwäbisch Gmünd',
             'Euskirchen',                'Freital',             'Wittenberg',
 'Garmisch-Partenkirchen',               'Miesbach',            'Wolmirstedt',
                'Pößneck',        'Schwäbisch Hall',                 'Dessau',
                 'Lübeck',              'Altötting',                 'Borken',
                  'Husum',                   'Jena',               'Cuxhaven',
                 'Weimar',                  'Rehau',                 'Anklam',
              'Eisenberg',         'Hildburghausen',               'Rathenow',
              'Spremberg',                  'Naila',           'Gunzenhausen',
                'München',            'Bersenbrück',            'Schlüchtern',
      'Ribnitz-Damgarten']
Length: 67, dtype: str
<StringArray>
['DE61756828670787846415', 'DE82457889219019323607', 'DE34416324838678344342',
 'DE82145213734298312066', 'DE22868934974325316861', 'DE50877513549189056170',
                      nan, 'DE23711364380199502979', 'DE27658313688646907154',
 'DE19547385530068574554', 'DE77213923661111451556', 'DE34912001255188069942',
 'DE24135847027624137434', 'DE88976553957418576735', 'DE82464336225692250408',
 'DE80462586702520077080', 'DE92591605710605264937', 'DE62771578489443956211',
 'DE42624414663978431978', 'DE38931223102677045064', 'DE14640790371644658403',
 'DE90563214082410667226', 'DE31494432263052273871', 'DE51707369728724921919',
 'DE62133310684893391333', 'DE68338419620982680612', 'DE86412885628076547868',
 'DE42460938803742894726', 'DE39638925681168799105', 'DE38336857473696809705',
 'DE06221952262082328894', 'DE17332345109978080630', 'DE92953822568468739569',
 'DE22342105126453957250', 'DE13156747192724518273', 'DE85989176758528303776',
 'DE66888269349630003601', 'DE74413782917015956678', 'DE45834229910647326921',
 'DE20509101726494390211', 'DE25204219581707558824', 'DE10637770240487365081',
 'DE75455812259571549447', 'DE90814506118573844353', 'DE16427978559400425463',
 'DE33409481437644507256', 'DE38331013834334468323', 'DE10311047921219431314',
 'DE05288772370963229353', 'DE82654037965434002807', 'DE30535632372090541619',
 'DE81682453452158809886', 'DE50976927680988638204', 'DE95896888950187276800',
 'DE53805602208224279925', 'DE15768805482374107438', 'DE95497690561653982165',
 'DE78809952661695186922', 'DE07739812065386591871', 'DE35311303430586784137',
 'DE62630078367771146999', 'DE57862945510350444348', 'DE16832084927712870800',
 'DE05125037714698616642', 'DE21772276980665898682', 'DE45815310655369788721',
 'DE61806120219135655356', 'DE88948907260834855904', 'DE56633860386512460412',
 'DE25994738544631934903', 'DE31889112932957084556', 'DE02108033289664719650',
 'DE92269538311202306933', 'DE95136993917430462301', 'DE98624960154356786873',
 'DE55117480141337509982', 'DE97332951796406441392']
Length: 77, dtype: str

# prüfung der spalten auf Speicherplatz.

In [ ]:

df.memory_usage()

Index                132
lieferanten_id       640
lieferanten_name     640
stadt                640
plz                  640
offizielle_iban      640
median_betrag_eur    640
streuung             640
dtype: int64

# leerezeichen am Anfang und Ende der Spalte lieferanten_name entfernen

In [ ]:

df['lieferanten_name'] = df['lieferanten_name'].str.strip()

In [17]:
df['lieferanten_name'].unique()

<StringArray>
[                               'Dowerg',
                 'Schäfer GmbH & Co. KG',
                              'Gumprich',
          'Holsten Förster AG & Co. OHG',
        'Beyer Vollbrecht GmbH & Co. KG',
                            'Tlustek AG',
                    'Metz Schuster GmbH',
                            'Vollbrecht',
                               'Hein AG',
                               'Ortmann',
                                 'Hesse',
                              'Wende AG',
                              'Mosemann',
             'Lübs Franke GmbH & Co. KG',
                               'Patberg',
                      'Niemeier Bähr AG',
                            'Neureuther',
                       'auch Schlauchin',
              'Dussen van Hentschel GbR',
            'Boucsein Stiftung & Co. KG',
        'Staude Neureuther AG & Co. OHG',
                 'Sorgatz GmbH & Co. KG',
                                 'Kambs',
                 'Holsten GmbH & Co. KG',
                            'Weller GbR',
                       'Adler Krebs GbR',
                          'Bohlander KG',
                                'Franke',
                'Dussen van Roskoth GbR',
        'Haase Staude Stiftung & Co. KG',
                  'Anders GmbH & Co. KG',
                          'Koch II GmbH',
                                  'Döhn',
                                'Häring',
                                'Löchel',
                                 'Trapp',
       'Säuberlich Rohleder AG & Co. KG',
                                'Hering',
        'Barth Gieß Stiftung & Co. KGaA',
            'Hartung Gute GmbH & Co. KG',
                    'Bohnbach Wirth GbR',
                              'Salz GbR',
                             'Krause KG',
             'Losekann Bohnbach OHG mbH',
                     'Kusch Textor GmbH',
                  'Rogge Ackermann GmbH',
          'Steuer Hamann GmbH & Co. OHG',
                           'Weitzel GbR',
                               'Wilmsen',
                            'Finke KGaA',
                              'Roht GbR',
 'Schmidtke Tschentscher GmbH & Co. OHG',
                               'Hofmann',
                     'Käster Juncken KG',
                       'Ladeck Kabus KG',
                                'Kramer',
                              'Hartmann',
                              'Stiebitz',
                   'Scheel Rose OHG mbH',
             'Junken Hahn GmbH & Co. KG',
                               'Weiß KG',
                   'Scholtz AG & Co. KG',
             'Geisel auch Schlauchin KG',
                                  'Kohl',
                               'Schinke',
                               'Seifert',
                              'Fliegner',
                                'Scheel',
                               'Schmidt',
                       'Heser Karge GbR',
                   'Röhricht Werner GbR',
                    'Süßebier Henk GmbH',
                     'Jäkel Hermann GbR',
                'Warmer GmbH & Co. KGaA',
                      'Jacobi Jäckel AG',
                             'Aumann KG',
                  'Drewes Bolzmann GmbH',
                             'Drubin KG',
                                 'Lorch',
                                 'Butte']
Length: 80, dtype: str

In [18]:
#speicherplatz problem: Wir haben 4 Spalten mit String Werten. Diese sind: 'lieferant_id', 'liferenten_name' 'stadt' und 'offizielle_iban'. 
# Wir können diese Spalten in den Datentyp 'category' umwandeln, um Speicherplatz zu sparen.
#category_columns = ['stadt', 'offizielle_iban']
#for col in category_columns:
    #df[col] = df[col].astype('category')
# alternativ df.loc[:, [2, 4]] = df.loc[:, [2, 4]].astype('category')

In [19]:
df.loc[:,'plz'].unique()

<StringArray>
['33218', '33890', '94026', '61559', '84959', '41316', '34192', '64835',
 '13953', '24238', '53287', '69166',     nan, '82814', '28809', '27824',
 '46578', '98393', '05183', '37631', '70106', '38726', '81080', '73602',
 '87234', '21913', '69985', '98084', '18244', '87401', '52427', '45053',
 '92322', '42160', '30365', '85014', '55698', '60883', '14846', '62994',
 '99577', '14895', '20037', '63287', '78895', '27743', '47143', '36231',
 '46688', '67065', '72980', '27204', '46417', '10033', '19374', '19049',
 '19314', '58651', '71657', '98776', '14737', '75273', '83136', '70143',
 '68557', '51823', '13435', '08427', '75204', '22941', '86774', '91334',
 '81206']
Length: 73, dtype: str

In [20]:
df.isna().sum()

lieferanten_id       0
lieferanten_name     0
stadt                5
plz                  8
offizielle_iban      4
median_betrag_eur    2
streuung             0
dtype: int64

# Spalte 'median_betrag_eur' hat 2 fehlende Werte. 
# Wir können diese Werte durch den Median der Spalte ersetzen, um die Daten zu bereinigen.
# spalte stadt und plz behandeln: Wir können die fehlenden Werte in der Spalte 'stadt' 
# und 'plz' durch den Wert 'unbekannt' ersetzen, um die Daten zu bereinigen.
# Die Spalte offizielle_iban hat 1 fehlenden Wert. 
# Wir können diesen Wert durch den Wert 'Fehlt' ersetzen,
# um die Daten zu bereinigen.

In [ ]:

gesamt_median = df['median_betrag_eur'].median()
#df['median_betrag_eur'] = df['median_betrag_eur'].astype(float).float.strip()
df['median_betrag_eur'] = df['median_betrag_eur'].fillna(gesamt_median)

df['stadt'] = df['stadt'].astype(str).str.strip()
df['stadt'] = df['stadt'].str.strip().replace(['', 'nan', 'NaN', 'None'], np.nan).fillna('Unbekannt')
df['plz'] = df['plz'].str.strip().replace(['', 'nan', 'NaN', 'None'], np.nan).fillna('0')

df['offizielle_iban'] = df['offizielle_iban'].str.strip().replace(['', 'nan', 'NaN', 'None'], np.nan).fillna('Fehlt')

In [22]:
df.isna().sum()

lieferanten_id       0
lieferanten_name     0
stadt                0
plz                  0
offizielle_iban      0
median_betrag_eur    0
streuung             0
dtype: int64

In [26]:
# alle Strin Datentyp als category umwandeln
for col in df.columns:
    if df[col].dtype == 'str':
        df[col] = df[col].astype('category')

In [27]:
df.dtypes

lieferanten_id       category
lieferanten_name     category
stadt                category
plz                  category
offizielle_iban      category
median_betrag_eur     float64
streuung              float64
dtype: object

# df als csv-Datei speichern

In [ ]:

df.to_csv('lieferanten_bereinigt.csv', index=False)